CREATE TABLE USERS (
    ID VARCHAR(256) NOT NULL,
    NAME VARCHAR(256),
    SALT VARCHAR(64) NOT NULL,
    PASSWORD VARCHAR(128),
    TIMEOUT BIGINT,
    ROLE VARCHAR(32),
    PRIMARY KEY(ID)
);
CREATE TABLE PERMISSIONS (
    ID VARCHAR(256) NOT NULL,
    ACTION VARCHAR(64),
    PATH VARCHAR(4000)
);
CREATE INDEX PermissionsIDIndex ON PERMISSIONS(ID);
CREATE INDEX PermissionsPathIndex ON PERMISSIONS(PATH)
