/* CVS $Id: $ */
package com.epimorphics.uklregistry.vocab; 
import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*;
 
/**
 * Vocabulary definitions from file:/home/der/projects/java-workspace/ukl/ukl-registry-poc/src/main/vocabs/version.ttl 
 * @author Auto-generated by schemagen on 23 Jan 2013 21:22 
 */
public class Version {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://purl.org/linked-data/version#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>The ontology's owl:versionInfo as a string</p> */
    public static final String VERSION_INFO = "0.1";
    
    /** <p>currentVersion relates an enduring resource to its current version</p> */
    public static final ObjectProperty currentVersion = m_model.createObjectProperty( "http://purl.org/linked-data/version#currentVersion" );
    
    /** <p>interval relates a thing version to an interval during which the version was 
     *  valid.</p>
     */
    public static final ObjectProperty interval = m_model.createObjectProperty( "http://purl.org/linked-data/version#interval" );
    
    /** <p>Indicates a property which does not change across versions of a VersionedThing</p> */
    public static final ObjectProperty rigidProperty = m_model.createObjectProperty( "http://purl.org/linked-data/version#rigidProperty" );
    
    /** <p>A version of a versioned thing.</p> */
    public static final OntClass Version = m_model.createClass( "http://purl.org/linked-data/version#Version" );
    
    /** <p>The class of things that can have multiple versions.</p> */
    public static final OntClass VersionedThing = m_model.createClass( "http://purl.org/linked-data/version#VersionedThing" );
    
}
